name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build DemoApi.Tests/DemoApi.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test DemoApi.Tests/DemoApi.Tests.csproj --no-restore --verbosity normal
